routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::check())
		return Redirect::route('estudiante.index');
	return Redirect::to('login');
});

Route::get('/login', 'LoginController@index')->name('login.index');
Route::post('/login', 'LoginController@store')->name('login.store');
Route::get('/logout', 'LoginController@logout')->name('logout');

// Route::get('/principal', function() {
//     return view('principal');
// })->name('principal');

Route::get('/estudiante', 'EstudianteController@index')->name('estudiante.index');
Route::get('/estudiante/create', 'EstudianteController@create')->name('estudiante.create');
Route::post('/estudiante/store', 'EstudianteController@store')->name('estudiante.store');
Route::get('/estudiante/{id}/edit', 'EstudianteController@edit')->name('estudiante.edit');
Route::post('/estudiante/{id}/update', 'EstudianteController@update')->name('estudiante.update');
Route::get('/estudiante/{id}/delete', 'EstudianteController@delete')->name('estudiante.delete');
Route::post('/estudiante/{id}/destroy', 'EstudianteController@destroy')->name('estudiante.destroy');
Route::post('/estudiante/search', 'EstudianteController@search')->name('estudiante.search');

Route::get('/acudiente', 'AcudienteController@index')->name('acudiente.index');
Route::get('/acudiente/create', 'AcudienteController@create')->name('acudiente.create');
Route::get('/acudiente/{id}/edit', 'AcudienteController@edit')->name('acudiente.edit');
Route::post('/acudiente/store', 'AcudienteController@store')->name('acudiente.store');
Route::post('/acudiente/{id}/update', 'AcudienteController@update')->name('acudiente.update');
Route::get('/acudiente/{id}/delete', 'AcudienteController@delete')->name('acudiente.delete');
Route::post('/acudiente/{id}/destroy', 'AcudienteController@destroy')->name('acudiente.destroy');
Route::post('/acudiente/search', 'AcudienteController@search')->name('acudiente.search');

Route::get('/colegio', 'ColegioController@index')->name('colegio.index');
Route::get('/colegio/create', 'ColegioController@create')->name('colegio.create');
Route::get('/colegio/{id}/edit', 'ColegioController@edit')->name('colegio.edit');
Route::post('/colegio/store', 'ColegioController@store')->name('colegio.store');
Route::post('/colegio/update', 'ColegioController@update')->name('colegio.update');

Route::get('/docente', 'DocenteController@index')->name('docente.index');
Route::get('/docente/create', 'DocenteController@create')->name('docente.create');
Route::get('/docente/{id}/edit', 'DocenteController@edit')->name('docente.edit');
Route::post('/docente/store', 'DocenteController@store')->name('docente.store');
Route::post('/docente/{id}/update', 'DocenteController@update')->name('docente.update');
Route::get('/docente/{id}/delete', 'DocenteController@delete')->name('docente.delete');
Route::post('/docente/{id}/destroy', 'DocenteController@destroy')->name('docente.destroy');
Route::post('/docente/search', 'DocenteController@search')->name('docente.search');

Route::get('/grado', 'GradoController@index')->name('grado.index');
Route::get('/grado/create', 'GradoController@create')->name('grado.create');
Route::get('/grado/{id}/show', 'GradoController@show')->name('grado.show');
Route::get('/grado/{id}/edit', 'GradoController@edit')->name('grado.edit');
Route::post('/grado/store', 'GradoController@store')->name('grado.store');
Route::post('/grado/{id}/update', 'GradoController@update')->name('grado.update');
Route::get('/grado/{id}/delete', 'GradoController@delete')->name('grado.delete');
Route::post('/grado/{id}/destroy', 'GradoController@destroy')->name('grado.destroy');

app/Acudiente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Acudiente extends Model
{
    use SoftDeletes;

    protected $table = 'acudientes';
    public $timestamps = true;

    protected $fillable = [
        "cedula_acudiente",
        "nombre_acudiente",
        "apellido_acudiente",
        "direccion_residencia",
        "colegio_id",
    ];
    protected $with = ['estudiante', 'telefonos'];

    public function estudiante() {
        return $this->hasMany('App\Estudiante', 'acudiente_id', 'id');
    }
    public function telefonos() {
        return $this->hasMany('App\Telefono', 'acudiente_id', 'id');
    }

	public function getNombreCompletoAcudienteAttribute() {
        return $this->attributes['nombre_acudiente'] . ' ' . $this->attributes['apellido_acudiente'];
	}

}

app/Docente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;

class Docente extends Model
{
    use SoftDeletes;

    protected $table = 'docentes';
    public $timestamps = true;

    protected $fillable = [
        "cedula_docente",
        "nombre_docente",
        "apellido_docente",
        "colegio_id",
    ];

	public function getNombreCompletoDocenteAttribute() {
        return $this->attributes['nombre_docente'] . ' ' . $this->attributes['apellido_docente'];
	}
}

app/Estudiante.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DateTime;

class Estudiante extends Model
{
    use SoftDeletes;

    protected $table = 'estudiantes';
    public $timestamps = true;

    protected $fillable = [
        "identificacion_estudiante",
        "nombre_estudiante",
        "apellido_estudiante",
        "sexo_estudiante",
        "fecha_nacimiento_estudiante",
        "colegio_id",
        "acudiente_id",
        "grado_id",
    ];
    protected $with = ['colegio'];

    public function colegio() {
        return $this->hasOne('App\Colegio', 'id', 'colegio_id');
    }

	public function getEdadAttribute() {
        $date = new DateTime($this->attributes['fecha_nacimiento_estudiante']);
        $now = new DateTime();
        $interval = $now->diff($date);
        return $interval->y;
	}

	public function getNombreCompletoEstudianteAttribute() {
        return $this->attributes['nombre_estudiante'] . ' ' . $this->attributes['apellido_estudiante'];
	}
}

app/Http/Controllers/EstudianteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Redirect;
use Auth;

class EstudianteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $estudiantes = \App\Estudiante::where('colegio_id', Auth::user()->id)->orderBy('nombre_estudiante')->get();
        $search = "";
        return view('estudiantes.list', compact('estudiantes', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $acudientes = \App\Acudiente::where('colegio_id', Auth::user()->id)->orderBy('nombre_acudiente')->get();
        $grados = \App\Grado::where('colegio_id', Auth::user()->id)->orderBy('nombre_grado')->get();
        return view('estudiantes.create', compact('acudientes', 'grados'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \App\Estudiante::create(array(
            "identificacion_estudiante" => $request['identificacion_estudiante'],
            "nombre_estudiante" => $request['nombre_estudiante'],
            "apellido_estudiante" => $request['apellido_estudiante'],
            "sexo_estudiante" => $request['sexo_estudiante'],
            "fecha_nacimiento_estudiante" => $request['fecha_nacimiento_estudiante'],
            "colegio_id" => Auth::user()->id,
            "acudiente_id" => ($request['acudiente_id'] != -1) ? $request['acudiente_id'] : null,
            "grado_id" => ($request['grado_id'] != -1) ? $request['grado_id'] : null,
        ));
        return Redirect::route('estudiante.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Colegio  $colegio
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Colegio  $colegio
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $estudiante = \App\Estudiante::findOrFail($id);
        $acudientes = \App\Acudiente::where('colegio_id', Auth::user()->id)->orderBy('nombre_acudiente')->get();
        $grados = \App\Grado::where('colegio_id', Auth::user()->id)->orderBy('nombre_grado')->get();
        return view('estudiantes.edit', compact('estudiante', 'acudientes', 'grados'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Colegio  $colegio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $estudiante = \App\Estudiante::findOrFail($id);
        $estudiante->identificacion_estudiante = $request['identificacion_estudiante'];
        $estudiante->nombre_estudiante = $request['nombre_estudiante'];
        $estudiante->apellido_estudiante = $request['apellido_estudiante'];
        $estudiante->sexo_estudiante = $request['sexo_estudiante'];
        $estudiante->fecha_nacimiento_estudiante = $request['fecha_nacimiento_estudiante'];
        $estudiante->acudiente_id = ($request['acudiente_id'] != -1) ? $request['acudiente_id'] : null;
        $estudiante->grado_id = ($request['grado_id'] != -1) ? $request['grado_id'] : null;
        $estudiante->save();
        return Redirect::route('estudiante.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Colegio  $colegio
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $estudiante = \App\Estudiante::findOrFail($id);
        return view('estudiantes.delete', compact('estudiante'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Colegio  $colegio
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $estudiante = \App\Estudiante::findOrFail($id);
        $estudiante->delete();
        return Redirect::route('estudiante.list');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $search = $request['search'];
        $val = '%' . $search . '%';
        $estudiantes = \App\Estudiante::where('colegio_id', Auth::user()->id)->where('identificacion_estudiante', 'like', $val)->orderBy('nombre_estudiante')->get();
        return view('estudiantes.list', compact('estudiantes', 'search'));
    }
}

resources/views/estudiantes/create.blade.php
@extends('layouts.default')

@section('content')
<div class="container">
  <h3>Estudiante</h3>

  <div class="login">
    <form action="{{route('estudiante.store')}}" method="POST">
      {!! csrf_field() !!}
      <h3>Registro del Estudiante</h3><hr>
      {{-- <div class="input-group-box">
        <label>Colegio</label>
        <select name="colegio_id" required>
          @foreach($colegios as $colegio)
          <option value="{{$colegio->id}}">{{$colegio->nombre_colegio}}</option>
          @endforeach
        </select>
      </div> --}}
      <div class="input-group-box">
        <label>Identificación Estudiante</label>
        <input type="text" name="identificacion_estudiante" required>
      </div>
      <div class="input-group-box">
        <label>Nombre del Estudiante</label>
        <input type="text" name="nombre_estudiante" required>
      </div>
      <div class="input-group-box">
        <label>Apellido del Estudiante</label>
        <input type="text" name="apellido_estudiante" required>
      </div>
      <div class="input-group-box">
        <label>Sexo del Estudiante</label>
        <select name="sexo_estudiante" required>
          <option value="MASCULINO" selected>Masculino</option>
          <option value="FEMENINO">Femenino</option>
        </select>
      </div>
      <div class="input-group-box">
        <label>Fecha de Nacimiento</label>
        <input type="date" name="fecha_nacimiento_estudiante" required>
      </div>
      <div class="input-group-box">
        <label>Acudiente</label>
        <select name="acudiente_id">
          <option value="-1" selected>Sin seleccionar</option>
          @foreach($acudientes as $acudiente)
          <option value="{{$acudiente->id}}">{{$acudiente->nombre_completo_acudiente}}</option>
          @endforeach
        </select>
      </div>
      <div class="input-group-box">
        <label>Grado</label>
        <select name="grado_id">
          <option value="-1" selected>Sin seleccionar</option>
          @foreach($grados as $grado)
          <option value="{{$grado->id}}">{{$grado->nombre_grado}} - {{$grado->docente->nombre_completo_docente}}</option>
          @endforeach
        </select>
      </div>
      <div class="buttons-box">
        <button type="button" class="red"><a href="{{route('estudiante.index')}}">Atras</a></button>
        <button type="submit">Guardar</button>
      </div>
    </form>
  </div>
</div>
@endsection

resources/views/estudiantes/delete.blade.php
@extends('layouts.default')

@section('content')
<div class="container">
  <h3>Estudiante</h3>

  <div class="login">
    <form action="{{route('estudiante.destroy', $estudiante->id)}}" id="deleteForm" method="POST">
      {!! csrf_field() !!}
      <h3>Eliminar Estudiante</h3><hr>
      <div class="input-group-box">
        <label>Identificación Estudiante</label>
        <input type="text" name="identificacion_estudiante" id="identificacion_estudiante" value="{{$estudiante->identificacion_estudiante}}" readonly>
      </div>
      <div class="input-group-box">
        <label>Ingresa el número de identificación del estudiante para confirmar la eliminacion</label>
        <input type="text" name="identificacion_estudiante_2" id="identificacion_estudiante_2" required>
      </div>
      <div class="buttons-box">
        <button type="button" class="red"><a href="{{route('estudiante.index')}}">Atras</a></button>
        <button type="submit">Guardar</button>
      </div>
    </form>
  </div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function(event) {
    const realVal = document.getElementById('identificacion_estudiante').value;
    const form = document.getElementById('deleteForm');
    form.addEventListener("submit", submitForm);
    function submitForm(e) {
      const val = document.getElementById('identificacion_estudiante_2').value;
      if(realVal != val) {
        console.log("NOPE");
        e.preventDefault();
      }
    }
  });
</script>
@endsection

resources/views/estudiantes/edit.blade.php
@extends('layouts.default')

@section('content')
<div class="container">
  <h3>Estudiante</h3>

  <div class="login">
    <form action="{{route('estudiante.update', $estudiante->id)}}" method="POST">
      {!! csrf_field() !!}
      <h3>Edición del Estudiante</h3><hr>
      <div class="input-group-box">
        <label>Identificación Estudiante</label>
        <input type="text" name="identificacion_estudiante" value="{{$estudiante->identificacion_estudiante}}" required>
      </div>
      <div class="input-group-box">
        <label>Nombre del Estudiante</label>
        <input type="text" name="nombre_estudiante" value="{{$estudiante->nombre_estudiante}}" required>
      </div>
      <div class="input-group-box">
        <label>Apellido del Estudiante</label>
        <input type="text" name="apellido_estudiante" value="{{$estudiante->apellido_estudiante}}" required>
      </div>
      <div class="input-group-box">
        <label>Sexo del Estudiante</label>
        <select name="sexo_estudiante" required>
          @if($estudiante->sexo_estudiante == 'MASCULINO')
          <option value="MASCULINO" selected>Masculino</option>
          <option value="FEMENINO">Femenino</option>
          @else
          <option value="MASCULINO">Masculino</option>
          <option value="FEMENINO" selected>Femenino</option>
          @endif
        </select>
      </div>
      <div class="input-group-box">
        <label>Fecha de Nacimiento</label>
        <input type="date" name="fecha_nacimiento_estudiante" value="{{$estudiante->fecha_nacimiento_estudiante}}" required>
      </div>
      <div class="input-group-box">
        <label>Acudiente</label>
        <select name="acudiente_id">
          <option value="-1" selected>Sin seleccionar</option>
          @foreach($acudientes as $acudiente)
          @if($acudiente->id == $estudiante->acudiente_id)
          <option value="{{$acudiente->id}}" selected>{{$acudiente->nombre_completo_acudiente}}</option>
          @else
          <option value="{{$acudiente->id}}">{{$acudiente->nombre_completo_acudiente}}</option>
          @endif
          @endforeach
        </select>
      </div>
      <div class="input-group-box">
        <label>Grado</label>
        <select name="grado_id">
          <option value="-1" selected>Sin seleccionar</option>
          @foreach($grados as $grado)
          @if($grado->id == $estudiante->grado_id)
          <option value="{{$grado->id}}" selected>{{$grado->nombre_grado}} - {{$grado->docente->nombre_completo_docente}}</option>
          @else
          <option value="{{$grado->id}}">{{$grado->nombre_grado}} - {{$grado->docente->nombre_completo_docente}}</option>
          @endif
          @endforeach
        </select>
      </div>
      <div class="buttons-box">
        <button type="button" class="red"><a href="{{route('estudiante.index')}}">Atras</a></button>
        <button type="submit">Guardar</button>
      </div>
    </form>
  </div>
</div>
@endsection

resources/views/estudiantes/list.blade.php
@extends('layouts.default')

@section('content')
<div class="container">
  <div class="top-box">
    <h3>Listado de Estudiantes</h3>
    <a href="{{route('estudiante.create')}}"><button>Nuevo estudiante</button></a>
  </div>
  <div class="clear"></div>
  <form action="{{route('estudiante.search')}}" id="searchForm" method="POST">
    {!! csrf_field() !!}
    <input type="text" name="search" value="{{$search}}" placeholder="Identificacion" required>
    <button type="submit">Buscar</button>
  </form>
  @if(count($estudiantes) > 0)
  <table>
    <thead>
      <tr>
        <th>Identificación</th>
        <th>Nombre</th>
        <th>Sexo</th>
        <th>Edad</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      @foreach($estudiantes as $estudiante)
      <tr>
        <td>{{$estudiante->identificacion_estudiante}}</td>
        <td>{{$estudiante->nombre_completo_estudiante}}</td>
        <td>{{$estudiante->sexo_estudiante}}</td>
        <td>{{$estudiante->edad}}</td>
        <td>
          <button><a href="{{route('estudiante.edit', $estudiante->id)}}">Editar</a></button>
          <button><a href="{{route('estudiante.delete', $estudiante->id)}}">Eliminar</a></button>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @else
  <div class="inside-box">
    <div class="box empty">
      <span>Sin resultados</span><br>
      <span>Por favor ingrese un nuevo registro</span>
    </div>
  </div>
  @endif
</div>
@endsection